### ISSUE TITLE
Cannot connect correctly using usb cable.

### ISSUE THREAD

**Issue by tasca73** [lichiukenneth/EV3Dev-Python-Socket-Connection#1]
I'm trying to use socket to control my EV3 device. The problem is, i can do that using wifi, but i can't do that using usb Ethernet. I use the exact python script( of course the IP is different). And i can use putty ssh my ev3. ev3 can ping the host. Is there anything else I can check?  Or how can i debug it?
![ev3dev.jpg](https://i.loli.net/2018/12/19/5c1a1e0e61c90.jpg)

**Comment by tasca73** [comment]
My English is bad. Thank you for your help!

**Comment by lichiukenneth** [comment]
Did you use the ev3 brick to run the program instead of running it using ssh?
There is a new version of this socket connection program, written by my student, you may take a look at it at his web site:
http://www.zephan.top

**Comment by lichiukenneth** [comment]
sorry, I was wrong, he didn’t put the socket program on that website.

**Comment by lichiukenneth** [comment]
I just checked my code, I think the code is fine.

When you said you can do it using WIFI, did you mean that you bought a WIFI Dongle and attached it to the EV3 brick?  I believe if the program can run in one Network Media, it should be fine in other network media as well, unless that media is blocked by some kind of firewall.

I use the USB cable provided by the EV3 set for program upload only, I did not try to use it as a network media to communicate between PC and the EV3.

**Comment by tasca73** [comment]
> I just checked my code, I think the code is fine.
> 
> When you said you can do it using WIFI, did you mean that you bought a WIFI Dongle and attached it to the EV3 brick? I believe if the program can run in one Network Media, it should be fine in other network media as well, unless that media is blocked by some kind of firewall.
> 
> I use the USB cable provided by the EV3 set for program upload only, I did not try to use it as a network media to communicate between PC and the EV3.

I bought a WIFI Dongle for my EV3 and attached it to the brick, so that the EV3 can access to the same network as the PC does. This way, the socket connected just fine.
Then I used the USB cable provided by the EV3 set as a network media, which is failed. 

The strange thing is, if I use my brick as the host, and my PC as my client, things will work out!

Maybe is the firewall blocking my EV3 from connecting to my PC. I am going to turn it off.

**Comment by tasca73** [comment]
I turn off the firewall. And it is okay now! Thank you very much!
